web:
    image: nginx:latest
    ports:
        - "8080:80" 
    volumes:
        - .:/var/www
        - ./nginx/conf:/etc/nginx/conf.d
    links:
        - php
    
php:
    image: php:7-fpm
    volumes:
        - .:/var/www